---
# tasks file for node_create
#
- name: Copy iso files to vcenter
  community.vmware.vsphere_copy:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    src: /tmp/{{ subdomain }}-{{ inventory_hostname_short }}.iso
    datacenter: "{{ datacenter_name }}"
    datastore: "{{ datastore_name }}"
    validate_certs: false
    path: iso/{{ subdomain }}-{{ inventory_hostname_short }}.iso
  delegate_to: localhost
  when: hostvars[inventory_hostname].platform == "vmware"

- name: Pause for upload
  ansible.builtin.pause:
    minutes: 1

- name: Create a virtual machine on given ESXi hostname
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    folder: "{{ subdomain }}"
    validate_certs: false
    name: "{{ subdomain }}-{{ inventory_hostname_short }}"
    state: poweredon
    guest_id: rhel8_64Guest
    cdrom:
    - controller_number: 0
      unit_number: 0
      state: present
      type: iso
      iso_path: "[{{ datastore_name }}]{{ iso_folder }}{{ subdomain }}-{{ inventory_hostname_short }}.iso"
    disk:
    - size_gb: 100
      type: thin
      datastore: "{{ datastore_name }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu_count }}"
      scsi: paravirtual
    networks:
    - name: "{{ vm_network }}"
      device_type: vmxnet3
      start_connected: true
  delegate_to: localhost
  when: hostvars[inventory_hostname].platform == "vmware"

- name: Pause for  minutes
  ansible.builtin.pause:
    minutes: 1
 
